In [1]:
# Get the necessary packages

!pip install esm
!pip install peft
!pip install bitsandbytes

from esm.models.esmc import ESMC
from esm.sdk.api import ESMProtein, LogitsConfig
import torch
import torch.nn as nn
from esm.tokenization import EsmSequenceTokenizer
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from peft import LoraConfig, get_peft_model
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import bitsandbytes as bnb
from tqdm import tqdm
from scipy import stats

Collecting esm
  Downloading esm-3.2.2.post2-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: torch>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from esm) (2.8.0+cu126)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from esm) (0.23.0+cu126)
Collecting torchtext (from esm)
  Downloading torchtext-0.18.0-cp312-cp312-manylinux1_x86_64.whl.metadata (7.9 kB)
Collecting transformers<4.48.2 (from esm)
  Downloading transformers-4.48.1-py3-none-any.whl.metadata (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 kB 3.6 MB/s eta 0:00:00
Requirement already satisfied: ipython in /usr/local/lib/python3.12/dist-packages (from esm) (7.34.0)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from esm) (0.8.1)
Collecting biotite>=1.0.0 (from esm)
  Downloading biotite-1.4.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.5 kB)
Collecting msgpack-numpy (from esm)
  Downloading msgpack_numpy-0.4.8-py2.py3-none-any.whl.metadata (5.0 kB)
Collecting biopython (from esm)
  Downloading biopython-1.85-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from esm) (1.6.1)
Requirement already satisfied: brotli in /usr/local/lib/python3.12/dist-packages (from esm) (1.1.0)
Requirement already satisfied: attrs in /usr/local/lib/python3.12/dist-packages (from esm) (25.4.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from esm) (2.2.2)
Requirement already satisfied: cloudpathlib in /usr/local/lib/python3.12/dist-packages (from esm) (0.23.0)
Requirement already satisfied: httpx in /usr/local/lib/python3.12/dist-packages (from esm) (0.28.1)
Requirement already satisfied: tenacity in /usr/local/lib/python3.12/dist-packages (from esm) (8.5.0)
Collecting zstd (from esm)
  Downloading zstd-1.5.7.2-cp312-cp312-manylinux_2_14_x86_64.whl.metadata (23 kB)
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.12/dist-packages (from esm) (7.7.1)
Collecting py3dmol (from esm)
  Downloading py3dmol-2.5.3-py2.py3-none-any.whl.metadata (2.1 kB)
Collecting pydssp (from esm)
  Downloading pydssp-0.9.1-py3-none-any.whl.metadata (4.9 kB)
Collecting boto3 (from esm)
  Downloading boto3-1.40.50-py3-none-any.whl.metadata (6.7 kB)
Collecting pygtrie (from esm)
  Downloading pygtrie-2.5.0-py3-none-any.whl.metadata (7.5 kB)
Collecting dna_features_viewer (from esm)
  Downloading dna_features_viewer-3.1.5-py3-none-any.whl.metadata (2.1 kB)
Collecting biotraj<2.0,>=1.0 (from biotite>=1.0.0->esm)
  Downloading biotraj-1.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (32 kB)
Requirement already satisfied: msgpack>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from biotite>=1.0.0->esm) (1.1.2)
Requirement already satisfied: networkx>=2.0 in /usr/local/lib/python3.12/dist-packages (from biotite>=1.0.0->esm) (3.5)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from biotite>=1.0.0->esm) (2.0.2)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.12/dist-packages (from biotite>=1.0.0->esm) (25.0)
Requirement already satisfied: requests>=2.12 in /usr/local/lib/python3.12/dist-packages (from biotite>=1.0.0->esm) (2.32.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (1.13.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (3.4.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from transformers<4.48.2->esm) (0.35.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers<4.48.2->esm) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<4.48.2->esm) (2024.11.6)
Collecting tokenizers<0.22,>=0.21 (from transformers<4.48.2->esm)
  Downloading tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers<4.48.2->esm) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers<4.48.2->esm) (4.67.1)
Collecting botocore<1.41.0,>=1.40.50 (from boto3->esm)
  Downloading botocore-1.40.50-py3-none-any.whl.metadata (5.7 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3->esm)
  Downloading jmespath-1.0.1-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.15.0,>=0.14.0 (from boto3->esm)
  Downloading s3transfer-0.14.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: matplotlib>=3 in /usr/local/lib/python3.12/dist-packages (from dna_features_viewer->esm) (3.10.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx->esm) (4.11.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx->esm) (2025.10.5)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx->esm) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx->esm) (3.10)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx->esm) (0.16.0)
Collecting jedi>=0.16 (from ipython->esm)
  Downloading jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython->esm) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython->esm) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.12/dist-packages (from ipython->esm) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython->esm) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython->esm) (2.19.2)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython->esm) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from ipython->esm) (0.1.7)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython->esm) (4.9.0)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->esm) (6.17.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->esm) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->esm) (3.6.10)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->esm) (3.0.15)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->esm) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->esm) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->esm) (2025.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->esm) (1.16.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->esm) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->esm) (3.6.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from torchvision->esm) (11.3.0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.12/dist-packages (from botocore<1.41.0,>=1.40.50->boto3->esm) (2.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.24.0->transformers<4.48.2->esm) (1.1.10)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->esm) (1.8.15)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->esm) (7.4.9)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->esm) (1.6.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->esm) (5.9.5)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->esm) (26.2.1)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->esm) (6.4.2)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython->esm) (0.8.5)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3->dna_features_viewer->esm) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3->dna_features_viewer->esm) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3->dna_features_viewer->esm) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3->dna_features_viewer->esm) (1.4.9)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3->dna_features_viewer->esm) (3.2.5)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython->esm) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->esm) (0.2.14)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->esm) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.12->biotite>=1.0.0->esm) (3.4.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.2.0->esm) (1.3.0)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.12/dist-packages (from widgetsnbextension~=3.6.0->ipywidgets->esm) (6.5.7)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from anyio->httpx->esm) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.2.0->esm) (3.0.3)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->esm) (0.4)
Requirement already satisfied: jupyter-core>=4.9.2 in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->esm) (5.8.1)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (25.1.0)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (5.10.4)
Requirement already satisfied: nbconvert>=5 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (7.16.6)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (1.8.3)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (0.23.1)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (1.3.3)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core>=4.9.2->jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->esm) (4.5.0)
Requirement already satisfied: notebook-shim>=0.2.3 in /usr/local/lib/python3.12/dist-packages (from nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (0.2.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (4.13.5)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (6.2.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (3.1.4)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (0.10.2)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (1.5.1)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (4.25.1)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.12/dist-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (25.1.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (1.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (0.27.1)
Requirement already satisfied: jupyter-server<3,>=1.8 in /usr/local/lib/python3.12/dist-packages (from notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (2.14.0)
Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (2.0.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (2.8)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (2.23)
Requirement already satisfied: jupyter-events>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (0.5.3)
Requirement already satisfied: overrides>=5.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (7.7.0)

In [2]:
# Set random seeds for reproducibility of your trainings run
def set_seeds(s):
    torch.manual_seed(s)
    np.random.seed(s)

set_seeds(42)

In [3]:
# Load the data
data = pd.read_csv("three_vs_rest.csv")
print(data)
data = data.rename(columns={"target": "label"})
# Split the data into train and test sets
train_df = data[data["set"]=="train"]
test_df = data[data["set"]=="test"]

train_df = train_df.drop(columns=["set","validation"])
test_df = test_df.drop(columns=["set","validation"])

# Print the shape of the data
print("Train set size:", train_df.shape[0])
print("Test set size:", test_df.shape[0])
# Print the columns of the data
print("Columns in train set and test set:", train_df.columns.tolist(), test_df.columns.tolist())

                                               sequence    target    set  \
0     MQYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGVDGEWTYD...  1.000000  train
1     MQYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGIDGEWTYD...  1.445905  train
2     MQYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGLDGEWTYD...  1.690164  train
3     MQYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGMDGEWTYD...  1.170550  train
4     MQYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGVAGEWTYD...  2.401243  train
...                                                 ...       ...    ...
8728  MQYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGYYSEWTYD...  0.368577   test
8729  MQYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGYYVEWTYD...  1.044870   test
8730  MQYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGYYVEWTYD...  0.002253   test
8731  MQYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGYYYEWTYD...  0.026282   test
8732  MQYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGYYYEWTYD...  0.004493   test

     validation
0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
...         ...
8728        NaN
8729        NaN
8730        NaN
8731        NaN
8732        NaN

[8733 rows x 4 columns]
Train set size: 2990
Test set size: 5743
Columns in train set and test set: ['sequence', 'label'] ['sequence', 'label']

In [4]:
## Tokenize the sequences

# Shuffle train_df
train_df = train_df.sample(frac=1, random_state=42)

# Reset the index of the shuffled DataFrame
train_df = train_df.reset_index(drop=True)

# Instantiate the tokenizer
tokenizer = EsmSequenceTokenizer()

# Pre-tokenize all sequences in the dataframe
train_df["tokenized_sequence"] = train_df["sequence"].apply(lambda seq: tokenizer(seq, return_tensors="pt"))
test_df["tokenized_sequence"] = test_df["sequence"].apply(lambda seq: tokenizer(seq, return_tensors="pt"))

# Define a PyTorch Dataset class for the sequences
class SequenceDataset(Dataset):
    """Custom PyTorch Dataset for protein sequences."""
    def __init__(self, dataframe):
        self.df = dataframe

    def __len__(self):
        return len(self.df)

    def __getitem__(self,idx):
        row = self.df.iloc[idx]
        sequence = row["sequence"]
        label = row["label"]
        # Use  the pre-tokenized sequence
        sequence_tensor = row["tokenized_sequence"]
        label_tensor = torch.tensor(row["label"], dtype=torch.float)
        return sequence_tensor, label_tensor

# Define a custom collate function to handle padding
def collate_fn(batch):
    """
    Collate function to pad sequences within a batch.
    """
    # batch is a list of tuples: [(sequence_tensor_1, label_tensor_1), (sequence_tensor_2, label_tensor_2), ...]
    sequences = [item[0] for item in batch]
    labels = torch.stack([item[1] for item in batch])

    # Pad the sequences to the maximum length in the batch
    # tokenizer returns a dictionary with 'input_ids' and 'attention_mask'
    input_ids = [seq['input_ids'].squeeze(0) for seq in sequences] # Remove the batch dimension from the tokenizer output
    attention_masks = [seq['attention_mask'].squeeze(0) for seq in sequences]

    # Pad input_ids and attention_masks
    padded_input_ids = torch.nn.utils.rnn.pad_sequence(input_ids, batch_first=True, padding_value=tokenizer.pad_token_id)
    padded_attention_masks = torch.nn.utils.rnn.pad_sequence(attention_masks, batch_first=True, padding_value=0) # Padding value for attention mask is 0

    # Recreate the dictionary structure expected by the model
    padded_sequences = {'input_ids': padded_input_ids, 'attention_mask': padded_attention_masks}

    return padded_sequences, labels

In [5]:
def train_step(model, dataloader, loss_fn, optimizer, device, accumulation_steps=1):
    """
    Trains a PyTorch model for a single epoch using regression loss.

    Args:
        model: A PyTorch model to be trained.
        dataloader: A DataLoader instance for the model to be trained on.
        loss_fn: A PyTorch loss function to minimize (e.g., MSELoss).
        optimizer: A PyTorch optimizer to help minimize the loss function.
        device: A target device to compute on (e.g., "cuda" or "cpu").
        accumulation_steps: The number of steps to accumulate gradients over.

    Returns:
        A float representing the average training loss over the epoch.
    """
    # Put model in train mode
    model.train()

    # Set train loss values
    train_loss = 0

    # Loop through data loader
    for batch, (sequence, labels) in enumerate(tqdm(dataloader, desc="Processing batches for training")):
        # Move sequence tensors and labels to the device
        sequence = {key: val.to(device) for key, val in sequence.items()}
        labels = labels.to(device)

        # Forward pass
        predictions = model(sequence)

        # Calculate loss and normalize for accumulation
        # Use .squeeze() to remove a dimension if the output is (batch_size, 1)
        loss = loss_fn(predictions.squeeze(), labels)

        # If performing gradient accumulation, normalize the loss
        if accumulation_steps > 1:
            loss = loss / accumulation_steps

        # Backward pass
        loss.backward()

        # Perform optimizer step and zero gradients only after accumulation_steps
        if (batch + 1) % accumulation_steps == 0 or (batch + 1) == len(dataloader):
            optimizer.step()
            optimizer.zero_grad()

        # Accumulate total loss before normalization
        train_loss += loss.item()

    # Get average metrics per batch
    train_loss = train_loss / len(dataloader)
    return train_loss

def test_step(model, dataloader, loss_fn, device):
    """
    Tests a PyTorch model for a single epoch and calculates regression metrics.

    Args:
        model: A PyTorch model to be tested.
        dataloader: A DataLoader instance for the model to be tested on.
        loss_fn: A PyTorch loss function to calculate loss on the test data.
        device: A target device to compute on (e.g., "cuda" or "cpu").

    Returns:
        A tuple of testing loss, validation loss and Spearman's rank correlation coefficient.
    """

    # Put model in eval mode
    model.eval()

    # Set test loss value
    test_loss = 0
    # Create lists for actual and predicted labels across all batches
    label_batch = []
    pred_batch = []

    with torch.inference_mode():
        # Loop through dataloader batches
        for batch, (sequence, labels) in enumerate(tqdm(dataloader, desc="Processing batches for testing")):
            # Move sequence tensors and labels to the device
            sequence = {key: val.to(device) for key, val in sequence.items()}
            labels = labels.to(device)

            # Forward pass
            predictions = model(sequence)

            # Calculate and accumulate loss
            # Use .squeeze() to remove a dimension if the output is (batch_size, 1)
            loss = loss_fn(predictions.squeeze(), labels)
            test_loss += loss.item()

            # Accumulate labels and predictions for global metric calculation
            label_batch.extend(labels.tolist())
            pred_batch.extend(predictions.squeeze().tolist())

    # Get average loss per batch
    test_loss = test_loss / len(dataloader)

    # Calculate overall regression metrics for all batches combined
    test_mae = mean_absolute_error(label_batch, pred_batch)
    spearmanr = round(stats.spearmanr(label_batch, pred_batch).statistic,6)


    # Return the calculated regression metrics
    return test_loss, spearmanr

In [6]:
def train(model, train_dataloader, test_dataloader, optimizer, loss_fn, epochs, device, accumulation_steps=1):
  """Trains and tests a PyTorch model.

    Args:
    model: A PyTorch model to be trained and tested.
    train_dataloader: A DataLoader instance for the model to be trained on.
    test_dataloader: A DataLoader instance for the model to be tested on.
    optimizer: A PyTorch optimizer to help minimize the loss function.
    loss_fn: A PyTorch loss function to calculate loss on both datasets.
    epochs: An integer indicating how many epochs to train for.
    device: A target device to compute on (e.g. "cuda" or "cpu").
    accumulation_steps: The number of steps to accumulate gradients over.
                            Default is 1 (no accumulation).

    Returns:
    A dictionary of training and testing loss as well as training and
    testing metrics. Each metric has a value in a list for each epoch.
    """

  results ={
      "Epoch": [],
      "Training Loss": [],
      "Validation Loss": [],
      "Spearmanr": []
  }

  # Set model type as float32 and transfer to device
  model.to(torch.float32).to(device)

  # Loop through training and testing steps for a number of epochs
  for epoch in range(epochs):
    train_loss = train_step(model=model,
                            dataloader=train_dataloader,
                            loss_fn=loss_fn,
                            optimizer=optimizer,
                            device=device,
                            accumulation_steps=accumulation_steps)
    test_loss, spearmanr = test_step(model=model,
                                    dataloader=test_dataloader,
                                    loss_fn=loss_fn,
                                    device=device)

    # Update results dictionary
    results["Epoch"].append(epoch + 1)
    results["Training Loss"].append(train_loss)
    results["Validation Loss"].append(test_loss)
    results["Spearmanr"].append(spearmanr)

    # Display results after each epoch
    epoch_results_df = pd.DataFrame({
        "Epoch": [epoch + 1],
        "Training Loss": [train_loss],
        "Validation Loss": [test_loss],
        "Spearmanr": [spearmanr]
    })
    display(epoch_results_df.set_index("Epoch"))

  # Return the results at the end of the epochs
  return results

In [7]:
# Define  modified ESMC model for protein sequence classification and regression tasks

class ESMC_SequenceClassification(nn.Module):
    '''ESMC model for sequence regression.
    Args:
        num_labels (int): Number of output labels for classification.
        model (ESMC): Pretrained ESMC model instance.
        num_features (int): Dimensionality of the model's output features
        dropout (float): Dropout rate for regularization.
    '''
    def __init__(self, num_labels, model, num_features, dropout=0.0):
        super(ESMC_SequenceClassification, self).__init__()
        self.num_labels = num_labels
        self.model = model
        self.dropout = dropout
        self.num_features = num_features
        self.classification_head = nn.Sequential(
            nn.Dropout(dropout),
            nn.Linear(num_features, num_features),
            nn.Tanh(),
            nn.Dropout(dropout),
            nn.Linear(num_features,num_labels)
            )


    # Modify forward to accept input_ids and attention_mask
    def forward(self, encoded_inputs):
        # Pass input_ids and attention_mask to the base ESM model's standard forward.
        attention_mask = None
        try:
            input_ids = encoded_inputs['input_ids']
            attention_mask = encoded_inputs['attention_mask']
        except KeyError:
             # If encoded_inputs is not a dictionary, assume it's just input_ids
             input_ids = encoded_inputs
             attention_mask = None # Set attention_mask to None if not provided

        # Pass input_ids and attention_mask to the underlying model
        outputs = self.model(sequence_tokens=input_ids, sequence_id=attention_mask)
        #seq_output = outputs.embeddings[:, 0, :]

         #Use mean pooling of the embeddings for sequence-level representation
         #outputs.embeddings will have shape (batch_size, sequence_length, hidden_size)
         #Apply attention mask during pooling
        if attention_mask is not None:
            # Mask out padding tokens before averaging
            masked_embeddings = outputs.embeddings * attention_mask.unsqueeze(-1)
            sum_embeddings = masked_embeddings.sum(dim=1)
            num_non_padded_tokens = attention_mask.sum(dim=1).unsqueeze(-1)
            # Avoid division by zero if a sequence is all padding
            num_non_padded_tokens = torch.max(num_non_padded_tokens, torch.ones_like(num_non_padded_tokens))
            pooled_output = sum_embeddings / num_non_padded_tokens
        else:
            pooled_output = outputs.embeddings.mean(dim=1) # Fallback if no attention mask

        logits = self.classification_head(pooled_output)
        return logits

In [8]:
# Function to get percentage of trainable parameters
def print_trainable_parameters(model):
    trainable_params, all_param = 0, 0
    for _, param in model.named_parameters():
        all_param += param.numel()
        if param.requires_grad:
            trainable_params += param.numel()
    print(f"trainable params: {trainable_params} || all params: {all_param} || trainable%: {100 * trainable_params / all_param:.2f}")

In [ ]:
## Transfer learning for regression task without fine tuning using ESMC 300M model

# Create datasets for training and testing
train_dataset = SequenceDataset(train_df)
test_dataset = SequenceDataset(test_df)


# Create DataLoaders for training and testing

train_loader = DataLoader(train_dataset, batch_size=8, shuffle=False, collate_fn=collate_fn, pin_memory=True,num_workers=2,persistent_workers=True)
test_loader = DataLoader(test_dataset, batch_size=8, shuffle=False, collate_fn=collate_fn, pin_memory=True,num_workers=2, persistent_workers=True)

# Load ESMC 300m model from pretrained
model = ESMC.from_pretrained("esmc_300m")

# Freeze all base layers in the model
for param in model.parameters():
    param.requires_grad = False

# Instantiate the ESMC_SequenceClassification model
model = ESMC_SequenceClassification(num_labels=1, model=model, num_features=960)

# Print trainable parameters
print_trainable_parameters(model)

# Select device
device = "cuda" if torch.cuda.is_available() else "cpu"

# Define loss and optimizer
loss_fn = nn.MSELoss()
optimizer = bnb.optim.PagedAdamW8bit(model.parameters(), lr=3e-4)

# Setup training and save the results
results = train(model=model,
                train_dataloader=train_loader,
                test_dataloader=test_loader,
                optimizer=optimizer,
                loss_fn=loss_fn,
                epochs=20,
                device=device)
results = pd.DataFrame(results)
results.to_csv("ESMC_300M_regression_training_logs.csv")

# Save the model state
PATH = "ESMC_300M_regression_model.pth"
torch.save(model.state_dict(), PATH)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

config.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

.gitattributes: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

data/weights/esmc_300m_2024_12_v0.pth:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

trainable params: 923521 || all params: 333920705 || trainable%: 0.28

Processing batches for training: 100%|██████████| 374/374 [02:51<00:00,  2.18it/s]
Processing batches for testing: 100%|██████████| 718/718 [05:33<00:00,  2.16it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
1           1.229248         1.622815   0.503673

Processing batches for training: 100%|██████████| 374/374 [02:53<00:00,  2.16it/s]
Processing batches for testing: 100%|██████████| 718/718 [05:32<00:00,  2.16it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
2           1.184739         1.590759   0.587266

Processing batches for training: 100%|██████████| 374/374 [02:53<00:00,  2.16it/s]
Processing batches for testing: 100%|██████████| 718/718 [05:32<00:00,  2.16it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
3           1.161571         1.544003   0.599251

Processing batches for training: 100%|██████████| 374/374 [02:53<00:00,  2.16it/s]
Processing batches for testing: 100%|██████████| 718/718 [05:32<00:00,  2.16it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
4           1.124909         1.503093   0.605042

Processing batches for training: 100%|██████████| 374/374 [02:53<00:00,  2.16it/s]
Processing batches for testing: 100%|██████████| 718/718 [05:32<00:00,  2.16it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
5           1.083293         1.467583    0.60985

Processing batches for training: 100%|██████████| 374/374 [02:53<00:00,  2.16it/s]
Processing batches for testing: 100%|██████████| 718/718 [05:32<00:00,  2.16it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
6           1.050701         1.418736   0.618095

Processing batches for training: 100%|██████████| 374/374 [02:53<00:00,  2.16it/s]
Processing batches for testing: 100%|██████████| 718/718 [05:32<00:00,  2.16it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
7           1.027243         1.382137   0.625815

Processing batches for training: 100%|██████████| 374/374 [02:53<00:00,  2.16it/s]
Processing batches for testing: 100%|██████████| 718/718 [05:33<00:00,  2.15it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
8           1.009596          1.35728   0.632807

Processing batches for training: 100%|██████████| 374/374 [02:53<00:00,  2.16it/s]
Processing batches for testing: 100%|██████████| 718/718 [05:32<00:00,  2.16it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
9            0.99504         1.338891   0.639315

Processing batches for training: 100%|██████████| 374/374 [02:53<00:00,  2.16it/s]
Processing batches for testing: 100%|██████████| 718/718 [05:33<00:00,  2.16it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
10          0.982367         1.323178   0.644675

Processing batches for training: 100%|██████████| 374/374 [02:53<00:00,  2.16it/s]
Processing batches for testing: 100%|██████████| 718/718 [05:33<00:00,  2.16it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
11           0.97124          1.30909    0.64948

Processing batches for training: 100%|██████████| 374/374 [02:53<00:00,  2.15it/s]
Processing batches for testing: 100%|██████████| 718/718 [05:33<00:00,  2.15it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
12          0.961045         1.296279   0.653587

Processing batches for training: 100%|██████████| 374/374 [02:53<00:00,  2.16it/s]
Processing batches for testing: 100%|██████████| 718/718 [05:32<00:00,  2.16it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
13          0.951947          1.28456   0.656185

Processing batches for training: 100%|██████████| 374/374 [02:53<00:00,  2.16it/s]
Processing batches for testing: 100%|██████████| 718/718 [05:33<00:00,  2.16it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
14          0.943291          1.27185   0.659351

Processing batches for training: 100%|██████████| 374/374 [02:53<00:00,  2.16it/s]
Processing batches for testing: 100%|██████████| 718/718 [05:32<00:00,  2.16it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
15          0.934941         1.258365   0.662006

Processing batches for training: 100%|██████████| 374/374 [02:53<00:00,  2.16it/s]
Processing batches for testing: 100%|██████████| 718/718 [05:32<00:00,  2.16it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
16          0.926912         1.243955   0.663856

Processing batches for training: 100%|██████████| 374/374 [02:53<00:00,  2.16it/s]
Processing batches for testing: 100%|██████████| 718/718 [05:32<00:00,  2.16it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
17          0.919196         1.229767   0.664833

Processing batches for training: 100%|██████████| 374/374 [02:53<00:00,  2.16it/s]
Processing batches for testing: 100%|██████████| 718/718 [05:33<00:00,  2.16it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
18          0.911817         1.216918   0.665627

Processing batches for training: 100%|██████████| 374/374 [02:53<00:00,  2.16it/s]
Processing batches for testing: 100%|██████████| 718/718 [05:32<00:00,  2.16it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
19          0.904842         1.204122   0.666546

Processing batches for training: 100%|██████████| 374/374 [02:53<00:00,  2.16it/s]
Processing batches for testing: 100%|██████████| 718/718 [05:33<00:00,  2.16it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
20          0.897863         1.191221   0.667337

In [ ]:
## Fine tuning for regression task using ESMC 300M model with LoRA

# Clear out GPU cache
torch.cuda.empty_cache()

# Create datasets for training and testing
train_dataset = SequenceDataset(train_df)
test_dataset = SequenceDataset(test_df)


# Create DataLoaders for training and testing

train_loader = DataLoader(train_dataset, batch_size=8, shuffle=False, collate_fn=collate_fn, pin_memory=True,num_workers=2,persistent_workers=True)
test_loader = DataLoader(test_dataset, batch_size=8, shuffle=False, collate_fn=collate_fn, pin_memory=True,num_workers=2, persistent_workers=True)

# Load the ESMC base model from pretrained using the custom class
base_esmc_model = ESMC.from_pretrained("esmc_300m")

# Define the LoRA configuration
lora_config = LoraConfig(
    r=4,
    lora_alpha=1,
    target_modules=[
        "layernorm_qkv.1",
        "out_proj",
        "ffn.1",
        "ffn.3"],
    bias="all"
)

# Use get_peft_model instead of inject_adapter_in_model
base_esmc_model = get_peft_model(base_esmc_model, lora_config)

# Instantiate the ESMC_SequenceClassification model
model = ESMC_SequenceClassification(num_labels=1, model= base_esmc_model, num_features=960)

# Print the trainable parameters
print_trainable_parameters(model)

# Select device
device = "cuda" if torch.cuda.is_available() else "cpu"

# Define loss and optimizer
loss_fn = nn.MSELoss()
optimizer = bnb.optim.PagedAdamW8bit(model.parameters(), lr=3e-4)

# Setup training and save the results
results = train(model=model,
                train_dataloader=train_loader,
                test_dataloader=test_loader,
                optimizer=optimizer,
                loss_fn=loss_fn,
                epochs=10,
                device=device)
results = pd.DataFrame(results)
results.to_csv("ESMC_300M_regression_training_logs_fine_tuned.csv")

# Save the model state
#PATH = "ESMC_300M_regression_model_fine_tuned.pth"
#torch.save(model.state_dict(), PATH)

## Saving checpoint for further training

# Define path and checkpoint content
PATH = "ESMC_300M_regression_model_fine_tuned_checkpoint.pth"
epoch = results["Epoch"].tail(1)
loss = results["Training Loss"].tail(1)

checkpoint = {
    'epoch': epoch,
    'model_state_dict': model.state_dict(),
    'optimizer_state_dict': optimizer.state_dict(),
    'loss': loss,
}

# Save the checkpoint
torch.save(checkpoint, PATH)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

README.md: 0.00B [00:00, ?B/s]

.gitattributes: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

data/weights/esmc_300m_2024_12_v0.pth:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

trainable params: 2826305 || all params: 335763905 || trainable%: 0.84

Processing batches for training: 100%|██████████| 374/374 [07:34<00:00,  1.21s/it]
Processing batches for testing: 100%|██████████| 718/718 [06:30<00:00,  1.84it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
1           1.215195         1.588392   0.356465

Processing batches for training: 100%|██████████| 374/374 [07:33<00:00,  1.21s/it]
Processing batches for testing: 100%|██████████| 718/718 [06:30<00:00,  1.84it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
2           1.004259         1.257214   0.586016

Processing batches for training: 100%|██████████| 374/374 [07:33<00:00,  1.21s/it]
Processing batches for testing: 100%|██████████| 718/718 [06:30<00:00,  1.84it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
3           0.659774         0.784944   0.842904

Processing batches for training: 100%|██████████| 374/374 [07:33<00:00,  1.21s/it]
Processing batches for testing: 100%|██████████| 718/718 [06:30<00:00,  1.84it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
4            0.42702         0.572005   0.865085

Processing batches for training: 100%|██████████| 374/374 [07:33<00:00,  1.21s/it]
Processing batches for testing: 100%|██████████| 718/718 [06:31<00:00,  1.84it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
5           0.293636          0.50033   0.869569

Processing batches for training: 100%|██████████| 374/374 [07:33<00:00,  1.21s/it]
Processing batches for testing: 100%|██████████| 718/718 [06:30<00:00,  1.84it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
6           0.209431         0.441813   0.877905

Processing batches for training: 100%|██████████| 374/374 [07:33<00:00,  1.21s/it]
Processing batches for testing: 100%|██████████| 718/718 [06:30<00:00,  1.84it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
7           0.158753         0.504896   0.871755

Processing batches for training: 100%|██████████| 374/374 [07:33<00:00,  1.21s/it]
Processing batches for testing: 100%|██████████| 718/718 [06:30<00:00,  1.84it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
8           0.138947         0.500531   0.874408

Processing batches for training: 100%|██████████| 374/374 [07:33<00:00,  1.21s/it]
Processing batches for testing: 100%|██████████| 718/718 [06:30<00:00,  1.84it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
9           0.111939         0.440575   0.879866

Processing batches for training: 100%|██████████| 374/374 [07:33<00:00,  1.21s/it]
Processing batches for testing: 100%|██████████| 718/718 [06:30<00:00,  1.84it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
10          0.100919         0.487311   0.871804

In [ ]:
## Transfer learning for regression task without fine tuning using ESMC 600M model

# Create datasets for training and testing
train_dataset = SequenceDataset(train_df)
test_dataset = SequenceDataset(test_df)


# Create DataLoaders for training and testing

train_loader = DataLoader(train_dataset, batch_size=8, shuffle=False, collate_fn=collate_fn, pin_memory=True,num_workers=2,persistent_workers=True)
test_loader = DataLoader(test_dataset, batch_size=8, shuffle=False, collate_fn=collate_fn, pin_memory=True,num_workers=2, persistent_workers=True)

# Load ESMC 300m model from pretrained
model = ESMC.from_pretrained("esmc_600m")

# Freeze all base layers in the model
for param in model.parameters():
    param.requires_grad = False

# Instantiate the ESMC_SequenceClassification model
model = ESMC_SequenceClassification(num_labels=1, model=model, num_features=1152)

# Print trainable parameters
print_trainable_parameters(model)

# Select device
device = "cuda" if torch.cuda.is_available() else "cpu"

# Define loss and optimizer
loss_fn = nn.MSELoss()
optimizer = bnb.optim.PagedAdamW8bit(model.parameters(), lr=3e-4)

# Setup training and save the results
results = train(model=model,
                train_dataloader=train_loader,
                test_dataloader=test_loader,
                optimizer=optimizer,
                loss_fn=loss_fn,
                epochs=10,
                device=device)
results = pd.DataFrame(results)
results.to_csv("ESMC_600M_regression_training_logs.csv")

# Save the model state
#PATH = "ESMC_600M_regression_model.pth"
#torch.save(model.state_dict(), PATH)

## Saving checpoint for further training

# Define path and checkpoint content
PATH = "ESMC_600M_regression_model_checkpoint.pth"
epoch = results["Epoch"].tail(1)
loss = results["Training Loss"].tail(1)

checkpoint = {
    'epoch': epoch,
    'model_state_dict': model.state_dict(),
    'optimizer_state_dict': optimizer.state_dict(),
    'loss': loss,
}

# Save the checkpoint
torch.save(checkpoint, PATH)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

.gitattributes: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

data/weights/esmc_600m_2024_12_v0.pth:   0%|          | 0.00/2.30G [00:00<?, ?B/s]

trainable params: 1329409 || all params: 576366401 || trainable%: 0.23

Processing batches for training: 100%|██████████| 374/374 [04:48<00:00,  1.29it/s]
Processing batches for testing: 100%|██████████| 718/718 [09:42<00:00,  1.23it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
1           1.218221         1.591928   0.464195

Processing batches for training: 100%|██████████| 374/374 [05:04<00:00,  1.23it/s]
Processing batches for testing: 100%|██████████| 718/718 [09:42<00:00,  1.23it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
2           1.148289         1.528529   0.504004

Processing batches for training: 100%|██████████| 374/374 [05:03<00:00,  1.23it/s]
Processing batches for testing: 100%|██████████| 718/718 [09:41<00:00,  1.23it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
3           1.090008         1.493663   0.536306

Processing batches for training: 100%|██████████| 374/374 [05:04<00:00,  1.23it/s]
Processing batches for testing: 100%|██████████| 718/718 [09:44<00:00,  1.23it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
4           1.033963         1.403771   0.571367

Processing batches for training: 100%|██████████| 374/374 [05:03<00:00,  1.23it/s]
Processing batches for testing: 100%|██████████| 718/718 [09:44<00:00,  1.23it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
5           0.989737         1.319793   0.594309

Processing batches for training: 100%|██████████| 374/374 [05:04<00:00,  1.23it/s]
Processing batches for testing: 100%|██████████| 718/718 [09:43<00:00,  1.23it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
6           0.956466          1.25933   0.610462

Processing batches for training: 100%|██████████| 374/374 [05:03<00:00,  1.23it/s]
Processing batches for testing: 100%|██████████| 718/718 [09:42<00:00,  1.23it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
7            0.93204         1.218275    0.62365

Processing batches for training: 100%|██████████| 374/374 [05:03<00:00,  1.23it/s]
Processing batches for testing: 100%|██████████| 718/718 [09:42<00:00,  1.23it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
8           0.913808          1.18298   0.637126

Processing batches for training: 100%|██████████| 374/374 [05:03<00:00,  1.23it/s]
Processing batches for testing: 100%|██████████| 718/718 [09:42<00:00,  1.23it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
9           0.899401         1.158697   0.646585

Processing batches for training: 100%|██████████| 374/374 [05:03<00:00,  1.23it/s]
Processing batches for testing: 100%|██████████| 718/718 [09:43<00:00,  1.23it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
10          0.887728         1.141293   0.653796

In [ ]:
## Fine tuning for regression task using ESMC 600M model with LoRA

# Clear out GPU cache
torch.cuda.empty_cache()

# Create datasets for training and testing
train_dataset = SequenceDataset(train_df)
test_dataset = SequenceDataset(test_df)


# Create DataLoaders for training and testing

train_loader = DataLoader(train_dataset, batch_size=8, shuffle=False, collate_fn=collate_fn, pin_memory=True,num_workers=2,persistent_workers=True)
test_loader = DataLoader(test_dataset, batch_size=8, shuffle=False, collate_fn=collate_fn, pin_memory=True,num_workers=2, persistent_workers=True)

# Load the ESMC base model from pretrained using the custom class
base_esmc_model = ESMC.from_pretrained("esmc_600m")

# Define the LoRA configuration
lora_config = LoraConfig(
    r=4,
    lora_alpha=1,
    target_modules=[
        "layernorm_qkv.1",
        "out_proj",
        "ffn.1",
        "ffn.3"],
    bias="all"
)

# Use get_peft_model instead of inject_adapter_in_model
base_esmc_model = get_peft_model(base_esmc_model, lora_config)

# Instantiate the ESMC_SequenceClassification model
model = ESMC_SequenceClassification(num_labels=1, model= base_esmc_model, num_features=1152)

# Print the trainable parameters
print_trainable_parameters(model)

# Select device
device = "cuda" if torch.cuda.is_available() else "cpu"

# Define loss and optimizer
loss_fn = nn.MSELoss()
optimizer = bnb.optim.PagedAdamW8bit(model.parameters(), lr=3e-4)

# Setup training and save the results
results = train(model=model,
                train_dataloader=train_loader,
                test_dataloader=test_loader,
                optimizer=optimizer,
                loss_fn=loss_fn,
                epochs=10,
                device=device)
results = pd.DataFrame(results)
results.to_csv("ESMC_600M_regression_training_logs_fine_tuned.csv")

# Save the model state
#PATH = "ESMC_600M_regression_model_fine_tuned.pth"
#torch.save(model.state_dict(), PATH)

## Saving checpoint for further training

# Define path and checkpoint content
PATH = "ESMC_600M_regression_model_fine_tuned_checkpoint.pth"
epoch = results["Epoch"].tail(1)
loss = results["Training Loss"].tail(1)

checkpoint = {
    'epoch': epoch,
    'model_state_dict': model.state_dict(),
    'optimizer_state_dict': optimizer.state_dict(),
    'loss': loss,
}

# Save the checkpoint
torch.save(checkpoint, PATH)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

.gitattributes: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

data/weights/esmc_600m_2024_12_v0.pth:   0%|          | 0.00/2.30G [00:00<?, ?B/s]

trainable params: 4068929 || all params: 579020609 || trainable%: 0.70

Processing batches for training: 100%|██████████| 374/374 [12:13<00:00,  1.96s/it]
Processing batches for testing: 100%|██████████| 718/718 [10:46<00:00,  1.11it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
1           1.227273         1.656482   0.499677

Processing batches for training: 100%|██████████| 374/374 [12:11<00:00,  1.96s/it]
Processing batches for testing: 100%|██████████| 718/718 [10:46<00:00,  1.11it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
2            1.19184         1.565908   0.465878

Processing batches for training: 100%|██████████| 374/374 [12:11<00:00,  1.96s/it]
Processing batches for testing: 100%|██████████| 718/718 [10:47<00:00,  1.11it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
3           0.949519         1.236828   0.657286

Processing batches for training: 100%|██████████| 374/374 [12:11<00:00,  1.96s/it]
Processing batches for testing: 100%|██████████| 718/718 [10:47<00:00,  1.11it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
4           0.731854         0.836176   0.804779

Processing batches for training: 100%|██████████| 374/374 [12:11<00:00,  1.96s/it]
Processing batches for testing: 100%|██████████| 718/718 [10:47<00:00,  1.11it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
5           0.562153         0.813458   0.829817

Processing batches for training: 100%|██████████| 374/374 [12:11<00:00,  1.96s/it]
Processing batches for testing: 100%|██████████| 718/718 [10:46<00:00,  1.11it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
6           0.466175         0.657624   0.841819

Processing batches for training: 100%|██████████| 374/374 [12:11<00:00,  1.96s/it]
Processing batches for testing: 100%|██████████| 718/718 [10:47<00:00,  1.11it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
7           0.376761         0.608435   0.854025

Processing batches for training: 100%|██████████| 374/374 [12:12<00:00,  1.96s/it]
Processing batches for testing: 100%|██████████| 718/718 [10:47<00:00,  1.11it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
8           0.292609         0.518748   0.861094

Processing batches for training: 100%|██████████| 374/374 [12:11<00:00,  1.96s/it]
Processing batches for testing: 100%|██████████| 718/718 [10:46<00:00,  1.11it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
9           0.249103         0.614609    0.86464

Processing batches for training: 100%|██████████| 374/374 [12:11<00:00,  1.96s/it]
Processing batches for testing: 100%|██████████| 718/718 [10:47<00:00,  1.11it/s]

       Training Loss  Validation Loss  Spearmanr
Epoch
10          0.222075         0.574152    0.87099